-- 1. Création de la Database et du Schéma
CREATE DATABASE IF NOT EXISTS E_COMMERCE_DB;
CREATE SCHEMA IF NOT EXISTS E_COMMERCE_DB.GOLD;
USE SCHEMA E_COMMERCE_DB.GOLD;


-- 1. Table Customers 
CREATE OR REPLACE TABLE DIM_CUSTOMERS (
    CUSTOMER_ID STRING,
    CUSTOMER_UNIQUE_ID STRING,
    CITY STRING,
    STATE STRING
);

-- 2. Table Products 
CREATE OR REPLACE TABLE DIM_PRODUCTS (
    PRODUCT_ID STRING,
    CATEGORY STRING,
    WEIGHT_G FLOAT
);

-- 3. Table de Faits 
CREATE OR REPLACE TABLE FACT_SALES (
    ORDER_ID STRING,
    PRODUCT_ID STRING,
    CUSTOMER_ID STRING,
    PRICE FLOAT,
    SALE_DATE TIMESTAMP
);

CREATE OR REPLACE STORAGE INTEGRATION s3_int
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'ton arn de rôle AWS'
  STORAGE_ALLOWED_LOCATIONS = ('s3://e-commerce-data-project-pipline/gold/');

-- RÉCUPÈRE LES INFOS GÉNÉRÉES
DESC INTEGRATION s3_int;
-- Création du stage
CREATE OR REPLACE STAGE my_s3_gold_stage
  STORAGE_INTEGRATION = s3_int
  URL = 's3://e-commerce-data-project-pipline/gold/'
  FILE_FORMAT = (TYPE = 'CSV' FIELD_DELIMITER = ',' SKIP_HEADER = 1);


